config/routes.rb
    end
    resources :time_entries, :controller => 'timelog'

    resources :wiki, :except => [:index, :new, :create] do
      collection do
        get :export
        get :date_index
        get '/index' => 'wiki#index'
      end

      member do
        get '/diff/:version/vs/:version_from' => 'wiki#diff', :as => 'wiki_diff'
        get '/diff(/:version)' => 'wiki#diff', :as => 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', :as => 'wiki_annotate'
        match :rename, :via => [:get, :put]
        get :parent_page, :action => 'edit_parent_page'
        put :parent_page, :action => 'update_parent_page'
        get :history
        post :preview
        post :protect
        post :add_attachment
        get  :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
      end
    end
    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => "wiki#show"

    namespace :work_packages do
      resources :calendar, :controller => 'calendars', :only => [:index]
    end

    resources :work_packages, :only => [:new, :create, :index] do
      get :new_type, :on => :collection
      put :preview, :on => :collection

      collection do
        match '/report/:detail' => 'work_packages/reports#report_details', :via => :get
        match '/report' => 'work_packages/reports#report', :via => :get
      end
    end

    resources :activity, :activities, :only => :index, :controller => 'activities'

    resources :boards do
      member do
        get :confirm_destroy
        get :move
        post :move
      end
    end

    resources :categories, :except => [:index, :show], :shallow => true

    resources :members, :only => [:create, :update, :destroy], :shallow => true do
      get :autocomplete, :on => :collection
    end

    resource :repository, :only => [:destroy] do
      get :edit #needed as show is configured manually with a wildcard
      post :edit
      get :committers
      post :committers
      get :graph
      get :revisions

      get "/statistics", :action => :stats, :as => 'stats'

      get '(/revisions/:rev)/diff.:format', :action => :diff
      get '(/revisions/:rev)/diff(/*path)', :action => :diff,
                                            :format => false

      get '(/revisions/:rev)/:format/*path', :action => :entry,
                                             :format => /raw/,
                                             :rev => /[a-z0-9\.\-_]+/

      %w{diff annotate changes entry browse}.each do |action|
        get "(/revisions/:rev)/#{action}(/*path)", :format => false,
                                                   :action => action,
                                                   :rev => /[a-z0-9\.\-_]+/
      end

      get '/revision(/:rev)', :rev => /[a-z0-9\.\-_]+/,
                              :action => :revision

      get '(/revisions/:rev)(/*path)', :action => :show,
                                       :format => false,
                                       :rev => /[a-z0-9\.\-_]+/

    end
  end

  #TODO: evaluate whether this can be turned into a namespace
  scope "admin" do
    match "/projects" => 'admin#projects', :via => :get

    resources :enumerations

    resources :groups do
      member do
        get :autocomplete_for_user
        #this should be put into it's own resource
        match "/members" => 'groups#add_users', :via => :post, :as => 'members_of'
        match "/members/:user_id" => 'groups#remove_user', :via => :delete, :as => 'member_of'
        #this should be put into it's own resource
        match "/memberships/:membership_id" => 'groups#edit_membership', :via => :put, :as => 'membership_of'
        match "/memberships/:membership_id" => 'groups#destroy_membership', :via => :delete, :as => 'membership_of'
        match "/memberships" => 'groups#create_memberships', :via => :post, :as => 'memberships_of'
      end
    end

    resources :roles, :only => [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        put '/' => 'roles#bulk_update'
        get :report
      end
    end

    resources :auth_sources, :ldap_auth_sources do
      member do
        get :test_connection
      end
    end
  end

  namespace :work_packages do
    match 'auto_complete' => 'auto_completes#index', :via => [:get, :post], :format => false
    match 'context_menu' => 'context_menus#index', :via => [:get, :post], :format => false
    resources :calendar, :controller => 'calendars', :only => [:index]
    resource :bulk, :controller => 'bulk', :only => [:edit, :update, :destroy]
  end

  resources :work_packages, :only => [:show, :edit, :update, :index] do
    get :new_type, :on => :member
    put :preview, :on => :member

    resources :relations, :controller => 'work_package_relations', :only => [:create, :destroy]

    # move bulk of wps
    get 'move/new' => 'work_packages/moves#new', :on => :collection, :as => 'new_move'
    post 'move' => 'work_packages/moves#create', :on => :collection, :as => 'move'
    # move individual wp
    resource :move, :controller => 'work_packages/moves', :only => [:new, :create]

    # this duplicate mapping is required for the timelog_helper
    namespace :time_entries do
      resource :report, :controller => 'reports'
    end
    resources :time_entries, :controller => 'timelog'
  end

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    member do
      get :status_by
    end
  end

  # Misc journal routes. TODO: move into resources
  match '/journals/:id/diff/:field' => 'journals#diff', :via => :get, :as => 'journal_diff'


  namespace :time_entries do
    resource :report, :controller => 'reports',
      :only => [:show]
  end

  resources :time_entries, :controller => 'timelog'

  resources :activity, :activities, :only => :index, :controller => 'activities'

  resources :users do
    member do
      match '/edit/:tab' => 'users#edit', :via => :get
      match '/memberships/:membership_id/destroy' => 'users#destroy_membership', :via => :post
      match '/memberships/:membership_id' => 'users#edit_membership', :via => :post
      match '/memberships' => 'users#edit_membership', :via => :post
      post :change_status
      post :edit_membership
      post :destroy_membership
      get :deletion_info
    end
  end

  resources :boards, :only => [] do
    resources :topics, :controller => 'messages', :except => [:index], :shallow => true do
      collection do
        post :preview
      end

      member do
        get :quote
        post :reply, :as => 'reply_to'
        post :preview
      end
    end
  end

  resources :news, :only => [:index, :destroy, :update, :edit, :show] do
    resources :comments, :controller => 'news/comments', :only => [:create, :destroy], :shallow => true

    resource :preview, :controller => 'news/previews', :only => [:create]
  end


  resources :attachments, :only => [:show, :destroy], :format => false do
    member do
      scope :via => :get,  :constraints => { :id => /\d+/, :filename => /[^\/]*/ } do
        match 'download(/:filename)' => 'attachments#download', :as => 'download'
        match ':filename' => 'attachments#show'
      end
    end
  end
  # redirect for backwards compatibility
  scope :constraints => { :id => /\d+/, :filename => /[^\/]*/ } do
    match "/attachments/download/:id/:filename" => redirect("/attachments/%{id}/download/%{filename}"), :format => false
    match "/attachments/download/:id" => redirect("/attachments/%{id}/download"), :format => false
  end

  scope :controller => 'sys' do
    match '/sys/projects.:format', :action => 'projects', :via => :get
    match '/sys/projects/:id/repository.:format', :action => 'create_project_repository', :via => :post
  end

  # alternate routes for the current user
  scope "my" do
    match '/deletion_info' => 'users#deletion_info', :via => :get, :as => 'delete_my_account_info'
  end

  scope :controller => 'my' do
    get '/my/password', :action => 'password'
    post '/my/change_password', :action => 'change_password'
  end

  get 'authentication' => 'authentication#index'

  resources :colors, :controller => 'planning_element_type_colors' do
     member do
       get :confirm_destroy
       get :move
       post :move
     end
  end

  resources :project_types, :controller => 'project_types' do
    member do
      get :confirm_destroy
      get :move
      post :move
    end

    resources :projects, :only => [:index, :show], :controller => 'projects'
    resources :reported_project_statuses,          :controller => 'reported_project_statuses'
  end

  resources :projects, :only => [:index, :show], :controller => 'projects' do
    resources :planning_elements,      :controller => 'planning_elements' do
      collection do
        get :all
        delete :destroy_all
        get :confirm_destroy_all
      end

      member do
        get :confirm_destroy
      end

      resources :journals, :controller => 'planning_element_journals',
                                           :only       => [:index, :create]
    end
    resources :project_associations,   :controller => 'project_associations' do
      get :confirm_destroy, :on => :member
      get :available_projects, :on => :collection
    end

    resources :reportings,             :controller => 'reportings' do
      get :confirm_destroy, :on => :member
    end

    resources :timelines,              :controller => 'timelines'
  end

  resources :reported_project_statuses, :controller => 'reported_project_statuses'

  # Install the default route as the lowest priority.
  match '/:controller(/:action(/:id))'
  match '/robots' => 'welcome#robots', :defaults => { :format => :txt }
  # Used for OpenID

app/models/group.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2013 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class Group < Principal
  has_many :group_users
  has_many :users, :through => :group_users,
                   :after_add => :user_added,
                   :after_remove => :user_removed

  acts_as_customizable

  validates_presence_of :lastname
  validates_uniqueness_of :lastname, :case_sensitive => false
  validates_length_of :lastname, :maximum => 30

  before_destroy :remove_references_before_destroy

  def to_s
    lastname.to_s
  end

  alias :name :to_s

  def user_added(user)
    members.each do |member|
      next if member.project.nil?

      user_member = Member.find_by_project_id_and_user_id(member.project_id, user.id)

      if user_member.nil?
        user_member = Member.new.tap do |m|
          m.project_id = member.project_id
          m.user_id = user.id
        end

        member.member_roles.each do |member_role|
          user_member.add_role(member_role.role, member_role.id)
        end

        user_member.save!
      else
        member.member_roles.each do |member_role|
          user_member.add_and_save_role(member_role.role, member_role.id)
        end
      end
    end
  end

  def user_removed(user)
    members.each do |member|
      MemberRole.find(:all,
        :include => :member,
        :conditions =>
          ["#{Member.table_name}.user_id = ? AND #{MemberRole.table_name}.inherited_from IN (?)",
            user.id, member.member_role_ids]).each do |member_role|
              member_role.member.remove_member_role_and_destroy_member_if_last(member_role)
            end
    end
  end

  # adds group members
  # meaning users that are members of the group
  def add_member!(users)
    self.users << users
  end

  private

  # Removes references that are not handled by associations
  def remove_references_before_destroy
    return if self.id.nil?

    deleted_user = DeletedUser.first

    WorkPackage.update_all({ :assigned_to_id => deleted_user.id },
                           { :assigned_to_id => id })

    Journal::WorkPackageJournal.update_all({ :assigned_to_id => deleted_user.id },
                                           { :assigned_to_id => id })
  end
end

app/helpers/groups_helper.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2013 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

module GroupsHelper
  def group_settings_tabs
    [{:name => 'general', :partial => 'groups/general', :label => :label_general},
     {:name => 'users', :partial => 'groups/users', :label => :label_user_plural},
     {:name => 'memberships', :partial => 'groups/memberships', :label => :label_project_plural}
     ]
  end
end

app/views/groups/_general.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= labelled_tabular_form_for @group, :url => group_path(@group), :html => {:method => :put}, :as => :group do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/groups/_memberships.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<% roles = Role.find_all_givable %>
<% projects = Project.active.find(:all, :order => 'lft') %>

<div class="splitcontentleft">
<% if @group.memberships.any? %>
<table class="list memberships">
	<thead><tr>
	  <th><%= Project.model_name.human %></th>
	  <th><%= l(:label_role_plural) %></th>
	  <th style="width:15%"></th>
	</tr></thead>
	<tbody>
	<% @group.memberships.each do |membership| %>
	<% next if membership.new_record? %>
	<tr id="member-<%= membership.id %>" class="<%= cycle 'odd', 'even' %> class">
	<td class="project"><%=h membership.project %></td>
  <td class="roles">
    <span id="member-<%= membership.id %>-roles"><%=h membership.roles.sort.collect(&:to_s).join(', ') %></span>
    <%= form_tag(membership_of_group_path(@group, membership),
                 :method => :put,
                 :remote => true,
                 :id => "member-#{membership.id}-roles-form",
                 :style => 'display:none;') do %>
      	<p><% roles.each do |role| %>
        <label><%= check_box_tag 'membership[role_ids][]', role.id, membership.roles.include?(role) %> <%=h role %></label><br />
        <% end %></p>
        <p><%= submit_tag l(:button_change) %>
        <%= link_to_function l(:button_cancel), "$('member-#{membership.id}-roles').show(); $('member-#{membership.id}-roles-form').hide(); return false;" %></p>
    <% end %>
  </td>
  <td class="buttons">
      <%= link_to_function l(:button_edit), "$('member-#{membership.id}-roles').hide(); $('member-#{membership.id}-roles-form').show(); return false;", :class => 'icon icon-edit' %>
      <%= link_to l(:button_delete), membership_of_group_path(@group, membership),
                                     :method => :delete,
                                     :remote => true,
                                     :class => 'icon icon-del' %>
  </td>
	</tr>
	</tbody>
<% end; reset_cycle %>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% if projects.any? %>
  <fieldset>
    <legend><%=l(:label_project_new)%></legend>
      <%= form_tag(memberships_of_group_path(@group),
                                             :method => :post,
                                             :remote => true) do %>
        <%= label_tag "membership_project_id", l(:description_choose_project), :class => "hidden-for-sighted" %>
        <%= select_tag 'membership[project_id]', options_for_membership_project_select(@group, projects) %>
        <p>
          <%= l(:label_role_plural) %>:
          <%= labeled_check_box_tags 'membership[role_ids][]', roles %>
        <p>
        <%= submit_tag l(:button_add) %></p>
      <% end %>
  </fieldset>
<% end %>
</div>

app/views/groups/_users.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<div class="splitcontentleft">
<% if @group.users.any? %>
	<table class="list users">
		<thead><tr>
		  <th><%= User.model_name.human %></th>
		  <th style="width:15%"></th>
		</tr></thead>
		<tbody>
		<% @group.users.sort.each do |user| %>
			<tr id="user-<%= user.id %>" class="<%= cycle 'odd', 'even' %>">
				<td class="user"><%= link_to_user user %></td>
			  <td class="buttons">
          <%= link_to l(:button_delete), member_of_group_path(@group, user),
                                         :method => :delete,
                                         :remote => :true,
                                         :class => 'icon icon-del' %>

			  </td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% else %>
	<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% users = User.active.not_in_group(@group).all(:limit => 100) %>
<% if users.any? %>
  <%= form_tag(members_of_group_path(@group), :method => :post, :remote => true) do |f| %>
    <fieldset><legend><%=l(:label_user_new)%></legend>

		<p><%= label_tag "user_search", l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>
		<%= observe_field(:user_search,
                      :frequency => 0.5,
                      :update => :users,
                      :url => { :controller => '/groups', :action => 'autocomplete_for_user', :id => @group },
                      :with => 'q',
                      :method => :get)
                  %>

		<div id="users">
			<%= principals_check_box_tags 'user_ids[]', users %>
		</div>

    <p><%= submit_tag l(:button_add) %></p>
		</fieldset>
  <% end %>
<% end %>

</div>

app/views/groups/autocomplete_for_user.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%= principals_check_box_tags 'user_ids[]', @users %>

app/views/groups/edit.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<h2><%= link_to l(:label_group_plural), groups_path %> &#187; <%= h(@group) %></h2>

<%= render_tabs group_settings_tabs %>

<% html_title( Group.model_name.human, @group, l(:label_administration)) -%>

app/views/groups/index.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<div class="contextual">
<%= link_to l(:label_group_new), new_group_path, :class => 'icon icon-add' %>
</div>

<h2><%= l(:label_group_plural) %></h2>

<% if @groups.any? %>
<table class="list groups">
  <thead><tr>
  <th><%= Group.model_name.human %></th>
  <th><%=l(:label_user_plural)%></th>
  <th></th>
  </tr></thead>
  <tbody>
<% @groups.each do |group| %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td><%= link_to h(group), :action => 'edit', :id => group %></td>
    <td align="center"><%= group.users.size %></td>
    <td class="buttons"><%= link_to l(:button_delete), group, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %></td>
  </tr>
<% end %>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/groups/new.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<h2><%= link_to l(:label_group_plural), groups_path %> &#187; <%= l(:label_group_new) %></h2>

<%= form_for(@group, :builder => TabularFormBuilder, :lang => current_language) do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<p><%= f.submit l(:button_create) %></p>
<% end %>