config/routes.rb
    end
    resources :time_entries, :controller => 'timelog'

    resources :wiki, :except => [:index, :new, :create] do
      collection do
        get :export
        get :date_index
        get '/index' => 'wiki#index'
      end

      member do
        get '/diff/:version/vs/:version_from' => 'wiki#diff', :as => 'wiki_diff'
        get '/diff(/:version)' => 'wiki#diff', :as => 'wiki_diff'
        get '/annotate/:version' => 'wiki#annotate', :as => 'wiki_annotate'
        match :rename, :via => [:get, :put]
        get :parent_page, :action => 'edit_parent_page'
        put :parent_page, :action => 'update_parent_page'
        get :history
        post :preview
        post :protect
        post :add_attachment
        get  :list_attachments
        get :select_main_menu_item, to: 'wiki_menu_items#select_main_menu_item'
        post :replace_main_menu_item, to: 'wiki_menu_items#replace_main_menu_item'
      end
    end
    # as routes for index and show are swapped
    # it is necessary to define the show action later
    # than any other route as it otherwise would
    # work as a catchall for everything under /wiki
    get 'wiki' => "wiki#show"

    namespace :work_packages do
      resources :calendar, :controller => 'calendars', :only => [:index]
    end

    resources :work_packages, :only => [:new, :create, :index] do
      get :new_type, :on => :collection
      put :preview, :on => :collection

      collection do
        match '/report/:detail' => 'work_packages/reports#report_details', :via => :get
        match '/report' => 'work_packages/reports#report', :via => :get
      end
    end

    resources :activity, :activities, :only => :index, :controller => 'activities'

    resources :boards do
      member do
        get :confirm_destroy
        get :move
        post :move
      end
    end

    resources :categories, :except => [:index, :show], :shallow => true

    resources :members, :only => [:create, :update, :destroy], :shallow => true do
      get :autocomplete, :on => :collection
    end

    resource :repository, :only => [:destroy] do
      get :edit #needed as show is configured manually with a wildcard
      post :edit
      get :committers
      post :committers
      get :graph
      get :revisions

      get "/statistics", :action => :stats, :as => 'stats'

      get '(/revisions/:rev)/diff.:format', :action => :diff
      get '(/revisions/:rev)/diff(/*path)', :action => :diff,
                                            :format => false

      get '(/revisions/:rev)/:format/*path', :action => :entry,
                                             :format => /raw/,
                                             :rev => /[a-z0-9\.\-_]+/

      %w{diff annotate changes entry browse}.each do |action|
        get "(/revisions/:rev)/#{action}(/*path)", :format => false,
                                                   :action => action,
                                                   :rev => /[a-z0-9\.\-_]+/
      end

      get '/revision(/:rev)', :rev => /[a-z0-9\.\-_]+/,
                              :action => :revision

      get '(/revisions/:rev)(/*path)', :action => :show,
                                       :format => false,
                                       :rev => /[a-z0-9\.\-_]+/

    end
  end

  #TODO: evaluate whether this can be turned into a namespace
  scope "admin" do
    match "/projects" => 'admin#projects', :via => :get

    resources :enumerations

    resources :groups do
      member do
        get :autocomplete_for_user
        #this should be put into it's own resource
        match "/members" => 'groups#add_users', :via => :post, :as => 'members_of'
        match "/members/:user_id" => 'groups#remove_user', :via => :delete, :as => 'member_of'
        #this should be put into it's own resource
        match "/memberships/:membership_id" => 'groups#edit_membership', :via => :put, :as => 'membership_of'
        match "/memberships/:membership_id" => 'groups#destroy_membership', :via => :delete, :as => 'membership_of'
        match "/memberships" => 'groups#create_memberships', :via => :post, :as => 'memberships_of'
      end
    end

    resources :roles, :only => [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        put '/' => 'roles#bulk_update'
        get :report
      end
    end

    resources :auth_sources, :ldap_auth_sources do
      member do
        get :test_connection
      end
    end
  end

  namespace :work_packages do
    match 'auto_complete' => 'auto_completes#index', :via => [:get, :post], :format => false
    match 'context_menu' => 'context_menus#index', :via => [:get, :post], :format => false
    resources :calendar, :controller => 'calendars', :only => [:index]
    resource :bulk, :controller => 'bulk', :only => [:edit, :update, :destroy]
  end

  resources :work_packages, :only => [:show, :edit, :update, :index] do
    get :new_type, :on => :member
    put :preview, :on => :member

    resources :relations, :controller => 'work_package_relations', :only => [:create, :destroy]

    # move bulk of wps
    get 'move/new' => 'work_packages/moves#new', :on => :collection, :as => 'new_move'
    post 'move' => 'work_packages/moves#create', :on => :collection, :as => 'move'
    # move individual wp
    resource :move, :controller => 'work_packages/moves', :only => [:new, :create]

    # this duplicate mapping is required for the timelog_helper
    namespace :time_entries do
      resource :report, :controller => 'reports'
    end
    resources :time_entries, :controller => 'timelog'
  end

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    member do
      get :status_by
    end
  end

  # Misc journal routes. TODO: move into resources
  match '/journals/:id/diff/:field' => 'journals#diff', :via => :get, :as => 'journal_diff'


  namespace :time_entries do
    resource :report, :controller => 'reports',
      :only => [:show]
  end

  resources :time_entries, :controller => 'timelog'

  resources :activity, :activities, :only => :index, :controller => 'activities'

  resources :users do
    member do
      match '/edit/:tab' => 'users#edit', :via => :get
      match '/memberships/:membership_id/destroy' => 'users#destroy_membership', :via => :post
      match '/memberships/:membership_id' => 'users#edit_membership', :via => :post
      match '/memberships' => 'users#edit_membership', :via => :post
      post :change_status
      post :edit_membership
      post :destroy_membership
      get :deletion_info
    end
  end

  resources :boards, :only => [] do
    resources :topics, :controller => 'messages', :except => [:index], :shallow => true do
      collection do
        post :preview
      end

      member do
        get :quote
        post :reply, :as => 'reply_to'
        post :preview
      end
    end
  end

  resources :news, :only => [:index, :destroy, :update, :edit, :show] do
    resources :comments, :controller => 'news/comments', :only => [:create, :destroy], :shallow => true

    resource :preview, :controller => 'news/previews', :only => [:create]
  end


  resources :attachments, :only => [:show, :destroy], :format => false do
    member do
      scope :via => :get,  :constraints => { :id => /\d+/, :filename => /[^\/]*/ } do
        match 'download(/:filename)' => 'attachments#download', :as => 'download'
        match ':filename' => 'attachments#show'
      end
    end
  end
  # redirect for backwards compatibility
  scope :constraints => { :id => /\d+/, :filename => /[^\/]*/ } do
    match "/attachments/download/:id/:filename" => redirect("/attachments/%{id}/download/%{filename}"), :format => false
    match "/attachments/download/:id" => redirect("/attachments/%{id}/download"), :format => false
  end

  scope :controller => 'sys' do
    match '/sys/projects.:format', :action => 'projects', :via => :get
    match '/sys/projects/:id/repository.:format', :action => 'create_project_repository', :via => :post
  end

  # alternate routes for the current user
  scope "my" do
    match '/deletion_info' => 'users#deletion_info', :via => :get, :as => 'delete_my_account_info'
  end

  scope :controller => 'my' do
    get '/my/password', :action => 'password'
    post '/my/change_password', :action => 'change_password'
  end

  get 'authentication' => 'authentication#index'

  resources :colors, :controller => 'planning_element_type_colors' do
     member do
       get :confirm_destroy
       get :move
       post :move
     end
  end

  resources :project_types, :controller => 'project_types' do
    member do
      get :confirm_destroy
      get :move
      post :move
    end

    resources :projects, :only => [:index, :show], :controller => 'projects'
    resources :reported_project_statuses,          :controller => 'reported_project_statuses'
  end

  resources :projects, :only => [:index, :show], :controller => 'projects' do
    resources :planning_elements,      :controller => 'planning_elements' do
      collection do
        get :all
        delete :destroy_all
        get :confirm_destroy_all
      end

      member do
        get :confirm_destroy
      end

      resources :journals, :controller => 'planning_element_journals',
                                           :only       => [:index, :create]
    end
    resources :project_associations,   :controller => 'project_associations' do
      get :confirm_destroy, :on => :member
      get :available_projects, :on => :collection
    end

    resources :reportings,             :controller => 'reportings' do
      get :confirm_destroy, :on => :member
    end

    resources :timelines,              :controller => 'timelines'
  end

  resources :reported_project_statuses, :controller => 'reported_project_statuses'

  # Install the default route as the lowest priority.
  match '/:controller(/:action(/:id))'
  match '/robots' => 'welcome#robots', :defaults => { :format => :txt }
  # Used for OpenID

app/controllers/work_packages/auto_completes_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2013 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class WorkPackages::AutoCompletesController < ApplicationController
  before_filter :find_project

  def index
    @work_packages = []
    q = params[:q].to_s

    if q.present?
      query = (params[:scope] == "all" && Setting.cross_project_work_package_relations?) ? WorkPackage : @project.work_packages

      @work_packages |= query.visible.find_all_by_id(q.to_i) if q =~ /\A\d+\z/

      @work_packages |= query.visible.find(:all,
                                           limit: 10,
                                           order: "#{WorkPackage.table_name}.id ASC",
                                           conditions: ["LOWER(#{WorkPackage.table_name}.subject) LIKE :q OR CAST(#{WorkPackage.table_name}.id AS CHAR(13)) LIKE :q", {q: "%#{q.downcase}%" }])
    end

    render layout: false
  end

  private

  def find_project
    project_id = (params[:work_package] && params[:work_package][:project_id]) || params[:project_id]
    @project = Project.find(project_id)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/controllers/work_packages/bulk_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2013 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

class WorkPackages::BulkController < ApplicationController
  before_filter :disable_api
  before_filter :find_work_packages
  before_filter :authorize

  include JournalsHelper
  include ProjectsHelper
  include CustomFieldsHelper
  include RelationsHelper
  include QueriesHelper
  include IssuesHelper

  def edit
    @work_packages.sort!
    @available_statuses = @projects.map{|p|Workflow.available_statuses(p)}.inject{|memo,w|memo & w}
    @custom_fields = @projects.map{|p|p.all_work_package_custom_fields}.inject{|memo,c|memo & c}
    @assignables = @projects.map(&:assignable_users).inject{|memo,a| memo & a}
    @types = @projects.map(&:types).inject{|memo,t| memo & t}
  end

  def update
    @work_packages.sort!
    attributes = parse_params_for_bulk_work_package_attributes(params)

    unsaved_work_package_ids = []
    @work_packages.each do |work_package|
      work_package.reload
      work_package.add_journal(User.current, params[:notes])
      work_package.safe_attributes = attributes
      call_hook(:controller_work_package_bulk_before_save, { params: params, work_package: work_package })
      JournalObserver.instance.send_notification = params[:send_notification] == '0' ? false : true
      unless work_package.save
        unsaved_work_package_ids << work_package.id
      end
    end
    set_flash_from_bulk_save(@work_packages, unsaved_work_package_ids)
    redirect_back_or_default({controller: '/work_packages', action: :index, project_id: @project})
  end

  def destroy
    unless WorkPackage.cleanup_associated_before_destructing_if_required(@work_packages, current_user, params[:to_do])

      respond_to do |format|
        format.html { render :locals => { work_packages: @work_packages,
                                          associated: WorkPackage.associated_classes_to_address_before_destruction_of(@work_packages) }
                    }
      end

    else

      destroy_work_packages(@work_packages)

      respond_to do |format|
        format.html { redirect_back_or_default(project_work_packages_path(@work_packages.first.project)) }
      end
    end
  end

private

  def destroy_work_packages(work_packages)
    work_packages.each do |work_package|
      begin
        work_package.reload.destroy
      rescue ::ActiveRecord::RecordNotFound
        # raised by #reload if work package no longer exists
        # nothing to do, work package was already deleted (eg. by a parent)
      end
    end
  end

  def parse_params_for_bulk_work_package_attributes(params)
    attributes = (params[:work_package] || {}).reject {|k,v| v.blank?}
    attributes.keys.each {|k| attributes[k] = '' if attributes[k] == 'none'}
    attributes[:custom_field_values].reject! {|k,v| v.blank?} if attributes[:custom_field_values]
    attributes.delete :custom_field_values if not attributes.has_key?(:custom_field_values) or attributes[:custom_field_values].empty?
    attributes
  end

  # Sets the `flash` notice or error based the number of work packages that did not save
  #
  # @param [Array, WorkPackage] work_packages all of the saved and unsaved WorkPackages
  # @param [Array, Integer] unsaved_work_package_ids the WorkPackage ids that were not saved
  def set_flash_from_bulk_save(work_packages, unsaved_work_package_ids)
    if unsaved_work_package_ids.empty?
      flash[:notice] = l(:notice_successful_update) unless work_packages.empty?
    else
      flash[:error] = l(:notice_failed_to_save_work_packages,
                        :count => unsaved_work_package_ids.size,
                        :total => work_packages.size,
                        :ids => '#' + unsaved_work_package_ids.join(', #'))
    end
  end

  def default_breadcrumb
    l(:label_work_package_plural)
  end
end

app/views/work_packages/bulk/destroy.html.erb
<h2><%= l(:label_confirmation) %></h2>

<%= error_messages_for work_packages.first %>

<%= form_tag work_packages_bulk_path, :method => :delete do %>
  <% work_packages.each do |work_package| %>
    <%= hidden_field_tag 'ids[]', work_package.id %>
  <% end %>

  <div class="box">

    <%= work_package_associations_to_address(associated) %>

    <p class="bold">
      <%= l(:text_destroy_what_to_do) %>
    </p>

    <%= fields_for :to_do do |f| %>
      <p>

        <%= f.radio_button 'action', 'destroy' %>
        <%= f.label 'action_destroy', l(:text_destroy) %>

      </p>
      <p>

        <%= f.radio_button 'action' , 'nullify' %>
        <%= f.label 'action_nullify', l(:text_assign_to_project) %>

      </p>
      <p>

        <%= f.radio_button 'action', 'reassign', :onclick => 'if(jQuery("#to_do_action_reassign").prop("checked")) { jQuery("#to_do_reassign_to_id").focus(); }' %>
        <%= f.label 'action_reassign', l(:text_reassign) %>

        <%= f.label 'reassign_to_id', l(:text_reassign_to) %>
        <%= f.text_field 'reassign_to_id', :value => params[:reassign_to_id], :size => 6, :onfocus => 'jQuery("#to_do_action_reassign").prop("checked", true);' %>

      </p>
    <% end %>
  </div>

  <%= submit_tag l(:button_apply) %>

<% end %>

app/views/work_packages/bulk/edit.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2013 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2013 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<h2><%= l(:label_bulk_edit_selected_work_packages) %></h2>

<ul><%= @work_packages.collect {|i| content_tag('li', link_to(h("#{i.type} ##{i.id}"), { :action => 'show', :id => i }) + h(": #{i.subject}")) }.join("\n").html_safe %></ul>

<%= form_tag(:action => 'update') do %>
<%= @work_packages.collect {|i| hidden_field_tag('ids[]', i.id)}.join.html_safe %>
<div class="box tabular">
<fieldset class="attributes">
<legend><%= l(:label_change_properties) %></legend>

<div class="splitcontentleft">
<p>
	<label for="work_package_type_id"><%= WorkPackage.human_attribute_name(:type) %></label>
	<%= select_tag('work_package[type_id]', "<option value=\"\">#{l(:label_no_change_option)}</option>".html_safe + options_from_collection_for_select(@types, :id, :name)) %>
</p>
<% if @available_statuses.any? %>
<p>
	<label for='status_id'><%= WorkPackage.human_attribute_name(:status) %></label>
	<%= select_tag('work_package[status_id]', "<option value=\"\">#{l(:label_no_change_option)}</option>".html_safe + options_from_collection_for_select(@available_statuses, :id, :name)) %>
</p>
<% end %>
<p>
	<label for='work_package_priority_id'><%= WorkPackage.human_attribute_name(:priority) %></label>
	<%= select_tag('work_package[priority_id]', "<option value=\"\">#{l(:label_no_change_option)}</option>".html_safe + options_from_collection_for_select(IssuePriority.all, :id, :name)) %>
</p>
<p>
	<label for='work_package_assigned_to_id'><%= WorkPackage.human_attribute_name(:assigned_to) %></label>
	<%= select_tag('work_package[assigned_to_id]', content_tag('option', l(:label_no_change_option), :value => '') +
                                 content_tag('option', l(:label_nobody), :value => 'none') +
                                 options_from_collection_for_select(@assignables, :id, :name)) %>
</p>
<% if @project %>
<p>
	<label for='category_id'><%= WorkPackage.human_attribute_name(:category) %></label>
	<%= select_tag('work_package[category_id]', content_tag('option', l(:label_no_change_option), :value => '') +
                                content_tag('option', l(:label_none), :value => 'none') +
                                options_from_collection_for_select(@project.categories, :id, :name)) %>
</p>
<% end %>
<% #TODO: allow editing versions when multiple projects %>
<% if @project %>
<p>
	<label for='work_package_fixed_version_id'><%= WorkPackage.human_attribute_name(:fixed_version) %></label>
	<%= select_tag('work_package[fixed_version_id]', content_tag('option', l(:label_no_change_option), :value => '') +
                                   content_tag('option', l(:label_none), :value => 'none') +
                                   version_options_for_select(@project.shared_versions.open.sort)) %>
</p>
<% end %>

<% @custom_fields.each do |custom_field| %>
  <p>
    <%= blank_custom_field_label_tag('work_package', custom_field) %>
    <%= custom_field_tag_for_bulk_edit('work_package', custom_field) %>
  </p>
<% end %>

<%= call_hook(:view_work_packages_bulk_edit_details_bottom, { work_packages: @work_packages }) %>
</div>

<div class="splitcontentright">
<% if @project && User.current.allowed_to?(:manage_subtasks, @project) %>
<p>
	<label for='work_package_parent_id'><%= WorkPackage.human_attribute_name(:parent) %></label>
	<%= text_field_tag 'work_package[parent_id]', '', :size => 10 %>
</p>
<div id="parent_work_package_candidates" class="autocomplete"></div>
<%= javascript_tag "observeParentIssueField('#{work_packages_auto_complete_path(project_id: @project.id)}')" %>
<% end %>
<p>
	<label for='work_package_start_date'><%= WorkPackage.human_attribute_name(:start_date) %></label>
	<%= text_field_tag 'work_package[start_date]', '', :size => 10 %><%= calendar_for('work_package_start_date') %>
</p>
<p>
	<label for='work_package_due_date'><%= WorkPackage.human_attribute_name(:due_date) %></label>
	<%= text_field_tag 'work_package[due_date]', '', :size => 10 %><%= calendar_for('work_package_due_date') %>
</p>
<% if WorkPackage.use_field_for_done_ratio? %>
<p>
	<label for='work_package_done_ratio'><%= WorkPackage.human_attribute_name(:done_ratio) %></label>
	<%= select_tag 'work_package[done_ratio]', options_for_select([[l(:label_no_change_option), '']] + (0..10).to_a.collect {|r| ["#{r*10} %", r*10] }) %>
</p>
<% end %>
</div>

</fieldset>

<fieldset><legend><%= Journal.human_attribute_name(:notes) %></legend>
<%= label_tag 'notes', Journal.human_attribute_name(:notes), :class => 'hidden-for-sighted' %>
<%= text_area_tag 'notes', @notes, :cols => 60, :rows => 10, :class => 'wiki-edit' %>
<%= wikitoolbar_for 'notes' %>
<%= send_notification_option %>
</fieldset>
</div>

<p><%= submit_tag l(:button_submit) %></p>
<% end %>